import dotenv from 'dotenv';
import { connectDB } from '../src/config/db.js';
import { CartItem } from '../src/models/CartItem.js';
import { Favorite } from '../src/models/Favorite.js';
import { Order } from '../src/models/Order.js';
import { Product } from '../src/models/Product.js';
import { getProductImagePath } from '../src/utils/productImages.js';

dotenv.config();

const products = [
  {
    name: 'Roma Tomatoes',
    category: 'Vegetable',
    price: 48,
    unit: 'kg',
    description: 'Firm and juicy tomatoes for salads, curries, pasta sauces, and daily kitchen prep.',
    imageUrl: getProductImagePath({ name: 'Roma Tomatoes' }),
    imageAlt: 'Fresh tomatoes and peppers arranged on a rustic wooden table.',
    supplier: 'SunFresh Valley',
    origin: 'Nashik, Maharashtra',
    packSize: '10 kg crate',
    stockLevel: 620,
    minOrderQty: 2,
    deliveryWindow: '30-45 mins',
    qualityGrade: 'Grade A',
    isOrganic: false,
    emoji: 'TM',
    color: '#e84a3c',
    tag: 'bestseller',
  },
  {
    name: 'Broccoli Crowns',
    category: 'Vegetable',
    price: 92,
    unit: 'kg',
    description: 'Crunchy premium broccoli with tight florets and long shelf life.',
    imageUrl: getProductImagePath({ name: 'Broccoli Crowns' }),
    imageAlt: 'Fresh broccoli placed on a white plate.',
    supplier: 'BlueHill Organics',
    origin: 'Ooty, Tamil Nadu',
    packSize: '8 kg carton',
    stockLevel: 180,
    minOrderQty: 1,
    deliveryWindow: '45 mins',
    qualityGrade: 'Premium',
    isOrganic: true,
    emoji: 'BR',
    color: '#4e8b57',
    tag: 'organic',
  },
  {
    name: 'English Cucumbers',
    category: 'Vegetable',
    price: 44,
    unit: 'kg',
    description: 'Hydrating long cucumbers with crisp bite and clean peel finish.',
    imageUrl: getProductImagePath({ name: 'English Cucumbers' }),
    imageAlt: 'Fresh cucumbers stacked together in a close-up view.',
    supplier: 'HydroLeaf Farms',
    origin: 'Bengaluru, Karnataka',
    packSize: '12 kg sleeve pack',
    stockLevel: 410,
    minOrderQty: 2,
    deliveryWindow: '30 mins',
    qualityGrade: 'Grade A',
    isOrganic: false,
    emoji: 'CU',
    color: '#74a25e',
    tag: null,
  },
  {
    name: 'Baby Spinach',
    category: 'Vegetable',
    price: 54,
    unit: 'bundle',
    description: 'Tender leafy spinach, perfect for saute, smoothies, salads, and soups.',
    imageUrl: getProductImagePath({ name: 'Baby Spinach' }),
    imageAlt: 'Fresh spinach leaves in a white bowl.',
    supplier: 'GreenNest Collective',
    origin: 'Pune, Maharashtra',
    packSize: '20 bundle sack',
    stockLevel: 260,
    minOrderQty: 2,
    deliveryWindow: '25 mins',
    qualityGrade: 'Leaf Select',
    isOrganic: true,
    emoji: 'SP',
    color: '#38975c',
    tag: 'organic',
  },
  {
    name: 'Rainbow Bell Peppers',
    category: 'Vegetable',
    price: 118,
    unit: 'kg',
    description: 'Bright mixed bell peppers for stir fries, salads, and snack platters.',
    imageUrl: getProductImagePath({ name: 'Rainbow Bell Peppers' }),
    imageAlt: 'Colorful bell peppers in red, yellow, and orange.',
    supplier: 'ColorCrop Farms',
    origin: 'Kodaikanal, Tamil Nadu',
    packSize: '5 kg premium crate',
    stockLevel: 145,
    minOrderQty: 1,
    deliveryWindow: '35 mins',
    qualityGrade: 'Premium',
    isOrganic: false,
    emoji: 'PP',
    color: '#f2a541',
    tag: 'premium',
  },
  {
    name: 'Red Onions',
    category: 'Vegetable',
    price: 28,
    unit: 'kg',
    description: 'Everyday kitchen staple with strong flavour and reliable freshness.',
    imageUrl: getProductImagePath({ name: 'Red Onions' }),
    imageAlt: 'Red onion and cut half onion placed on a clean surface.',
    supplier: 'Mandai Produce Hub',
    origin: 'Solapur, Maharashtra',
    packSize: '25 kg sack',
    stockLevel: 1100,
    minOrderQty: 3,
    deliveryWindow: '20 mins',
    qualityGrade: 'Daily Fresh',
    isOrganic: false,
    emoji: 'ON',
    color: '#a44a6a',
    tag: null,
  },
  {
    name: 'Sweet Corn Cobs',
    category: 'Vegetable',
    price: 18,
    unit: 'piece',
    description: 'Fresh yellow corn cobs for roasting, soups, and quick snack prep.',
    imageUrl: getProductImagePath({ name: 'Sweet Corn Cobs' }),
    imageAlt: 'Fresh sweet corn cobs displayed at a market.',
    supplier: 'Harvest Point',
    origin: 'Mysuru, Karnataka',
    packSize: '12 piece tray',
    stockLevel: 520,
    minOrderQty: 4,
    deliveryWindow: '25 mins',
    qualityGrade: 'Season Select',
    isOrganic: false,
    emoji: 'SC',
    color: '#d5aa2c',
    tag: 'seasonal',
  },
  {
    name: 'Purple Cabbage',
    category: 'Vegetable',
    price: 46,
    unit: 'kg',
    description: 'Dense purple cabbage with crisp texture and vibrant color for salads.',
    imageUrl: getProductImagePath({ name: 'Purple Cabbage' }),
    imageAlt: 'Close-up of a purple cabbage in a garden setting.',
    supplier: 'PeakFarm Produce',
    origin: 'Shimla, Himachal Pradesh',
    packSize: '14 kg crate',
    stockLevel: 190,
    minOrderQty: 1,
    deliveryWindow: '40 mins',
    qualityGrade: 'Grade A',
    isOrganic: false,
    emoji: 'CB',
    color: '#7d5ba6',
    tag: 'new',
  },
  {
    name: 'Alphonso Mango',
    category: 'Fruit',
    price: 180,
    unit: 'kg',
    description: 'Rich, fragrant Alphonso mango with creamy flesh and peak sweetness.',
    imageUrl: getProductImagePath({ name: 'Alphonso Mango' }),
    imageAlt: 'Single ripe mango on a light background.',
    supplier: 'Konkan Gold Estates',
    origin: 'Ratnagiri, Maharashtra',
    packSize: '4 kg box',
    stockLevel: 130,
    minOrderQty: 1,
    deliveryWindow: '35 mins',
    qualityGrade: 'Export Select',
    isOrganic: false,
    emoji: 'MG',
    color: '#f4a259',
    tag: 'premium',
  },
  {
    name: 'Cavendish Banana',
    category: 'Fruit',
    price: 52,
    unit: 'dozen',
    description: 'Sweet everyday bananas for breakfast bowls, shakes, and snacks.',
    imageUrl: getProductImagePath({ name: 'Cavendish Banana' }),
    imageAlt: 'Fresh yellow bananas displayed at a market.',
    supplier: 'South Orchard Link',
    origin: 'Erode, Tamil Nadu',
    packSize: '1 dozen bunch',
    stockLevel: 680,
    minOrderQty: 1,
    deliveryWindow: '15 mins',
    qualityGrade: 'Retail Ready',
    isOrganic: false,
    emoji: 'BN',
    color: '#f7c948',
    tag: 'bestseller',
  },
  {
    name: 'Green Grapes',
    category: 'Fruit',
    price: 138,
    unit: 'kg',
    description: 'Crunchy seedless grapes with balanced sweetness and premium finish.',
    imageUrl: getProductImagePath({ name: 'Green Grapes' }),
    imageAlt: 'Fresh grapes with leaves and water droplets.',
    supplier: 'VineRoute Growers',
    origin: 'Sangli, Maharashtra',
    packSize: '6 kg clamshell case',
    stockLevel: 240,
    minOrderQty: 1,
    deliveryWindow: '35 mins',
    qualityGrade: 'Premium',
    isOrganic: false,
    emoji: 'GP',
    color: '#8ab17d',
    tag: null,
  },
  {
    name: 'Pomegranate',
    category: 'Fruit',
    price: 104,
    unit: 'piece',
    description: 'Juicy ruby pomegranate with bold colour and naturally sweet-tart seeds.',
    imageUrl: getProductImagePath({ name: 'Pomegranate' }),
    imageAlt: 'Split pomegranate showing bright red seeds.',
    supplier: 'Ruby Field Produce',
    origin: 'Bijapur, Karnataka',
    packSize: '6 piece tray',
    stockLevel: 320,
    minOrderQty: 2,
    deliveryWindow: '30 mins',
    qualityGrade: 'Grade A',
    isOrganic: true,
    emoji: 'PG',
    color: '#b23a48',
    tag: 'organic',
  },
  {
    name: 'Watermelon',
    category: 'Fruit',
    price: 22,
    unit: 'kg',
    description: 'Cooling summer watermelon with deep sweetness and high freshness.',
    imageUrl: getProductImagePath({ name: 'Watermelon' }),
    imageAlt: 'Whole fresh watermelon with water droplets on a white background.',
    supplier: 'SummerPatch Farms',
    origin: 'Anantapur, Andhra Pradesh',
    packSize: 'Loose whole fruit',
    stockLevel: 980,
    minOrderQty: 1,
    deliveryWindow: '25 mins',
    qualityGrade: 'Farm Fresh',
    isOrganic: false,
    emoji: 'WM',
    color: '#e56b6f',
    tag: 'seasonal',
  },
  {
    name: 'Strawberries',
    category: 'Fruit',
    price: 168,
    unit: 'kg',
    description: 'Bright strawberries with juicy bite and dessert-friendly sweetness.',
    imageUrl: getProductImagePath({ name: 'Strawberries' }),
    imageAlt: 'Top view of fresh strawberries on a white background.',
    supplier: 'BerryMist Farms',
    origin: 'Mahabaleshwar, Maharashtra',
    packSize: '12 punnet case',
    stockLevel: 96,
    minOrderQty: 1,
    deliveryWindow: '20 mins',
    qualityGrade: 'Premium',
    isOrganic: false,
    emoji: 'ST',
    color: '#e63946',
    tag: 'seasonal',
  },
  {
    name: 'Pink Guava',
    category: 'Fruit',
    price: 74,
    unit: 'kg',
    description: 'Fresh guava with fragrant aroma, pink flesh, and tropical sweetness.',
    imageUrl: getProductImagePath({ name: 'Pink Guava' }),
    imageAlt: 'Whole and cut guava fruits on a bright backdrop.',
    supplier: 'Orchard South',
    origin: 'Allahabad, Uttar Pradesh',
    packSize: '5 kg tray',
    stockLevel: 275,
    minOrderQty: 1,
    deliveryWindow: '30 mins',
    qualityGrade: 'Grade A',
    isOrganic: false,
    emoji: 'GV',
    color: '#f28482',
    tag: 'new',
  },
  {
    name: 'Dragon Fruit',
    category: 'Fruit',
    price: 210,
    unit: 'piece',
    description: 'Exotic dragon fruit with vibrant pink skin and refreshing mild sweetness.',
    imageUrl: getProductImagePath({ name: 'Dragon Fruit' }),
    imageAlt: 'Fresh dragon fruit on a neutral surface.',
    supplier: 'Exotic Harvest Network',
    origin: 'Pune, Maharashtra',
    packSize: '4 piece box',
    stockLevel: 88,
    minOrderQty: 1,
    deliveryWindow: '45 mins',
    qualityGrade: 'Premium',
    isOrganic: false,
    emoji: 'DF',
    color: '#d95dad',
    tag: 'premium',
  },
];

const seedProducts = async () => {
  try {
    if (!process.env.MONGO_URI) {
      throw new Error('MONGO_URI is not defined in the environment.');
    }

    await connectDB();

    await Order.deleteMany({});
    await CartItem.deleteMany({});
    await Favorite.deleteMany({});
    await Product.deleteMany({});
    await Product.insertMany(products);

    console.log('Seeded 16 storefront-ready products with real images.');
    process.exit(0);
  } catch (error) {
    console.error(`Failed to seed products: ${error.message}`);
    process.exit(1);
  }
};

await seedProducts();
